spring:
  application:
    name: scholarsearch
  profiles:
    active: ${spring.active_profile}
  mvc:
    # noinspection SpellCheckingInspection
    problemdetails:
      enabled: true
  docker:
    compose:
      enabled: false
custom:
  semantic-scholar:
    paper:
      relevance-search-url: ${semantic_scholar.paper.relevance_search_url}
      details-search-url: ${semantic_scholar.paper.details_search_url}
